### ISSUE TITLE
[C#] Unit tests

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1041]
Test results at #1040: https://github.com/microsoft/teams-ai/suites/18852945301/artifacts/1099928226
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1053
- [ ] https://github.com/microsoft/teams-ai/issues/1114
- [ ] https://github.com/microsoft/teams-ai/issues/1117
- [ ] https://github.com/microsoft/teams-ai/issues/1115
- [ ] https://github.com/microsoft/teams-ai/issues/1116
- [ ] https://github.com/microsoft/teams-ai/issues/1120
- [ ] https://github.com/microsoft/teams-ai/issues/1119
- [ ] https://github.com/microsoft/teams-ai/issues/907
```
