### ISSUE TITLE
[PY] Authentication - GA

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1074]
implement `authentication` functionality of `JS` SDK https://github.com/microsoft/teams-ai/tree/main/js/packages/teams-ai/src/authentication
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1312
- [ ] https://github.com/microsoft/teams-ai/issues/1317
- [ ] https://github.com/microsoft/teams-ai/issues/1494
- [ ] https://github.com/microsoft/teams-ai/issues/1313
- [ ] https://github.com/microsoft/teams-ai/issues/1625
```
#788

**Comment by lilyydu** [comment]
*classes mentioned per point can be done in parallel
*suggested to reference C# code instead of JS

1. IAuthentication interface
2. UserTokenClientWrapper ,TurnStateProperty & AuthUtilities classes. They are utility classes that can be done in parallel.
3. OAuthAuthentication and TeamsSSOAuthentication class. You can stub non-trivial dependencies for now. These two can be done in parallel. These classes host all the auth business logic. Think of it as a wrapper around code that users would've otherwise had to implement themselves when using BF sdk.
4. Bot/ and MessageExtensions/ folder. Contains all business logic for bot auth and me auth. They can be done in parallel. Instead of diving the work by "OAuth" and "TeamsSSO" i recommend one person implement both of them for either Bot or ME scenario cause a lot of the logic overlaps. 
5. AuthenticationManager class
6. Application class
7. All the samples except adaptive card sample. This one you could divide by OAuth and TeamsSSO.
8. Add the AdaptiveCard auth logic as well.

 
C# doesn't have AdaptiveCard auth implemented but JS does
