### ISSUE TITLE
OpenAI Vision

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1096]
add support for openai vision api https://platform.openai.com/docs/guides/vision to SDK
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1017
- [ ] https://github.com/microsoft/teams-ai/issues/1011
- [ ] https://github.com/microsoft/teams-ai/issues/912
- [ ] https://github.com/microsoft/teams-ai/pull/1018
```

**Comment by corinagum** [comment]
Closing as all items are resolved
