### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1100]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/732
- [ ] https://github.com/microsoft/teams-ai/issues/733
- [ ] https://github.com/microsoft/teams-ai/issues/734
- [ ] https://github.com/microsoft/teams-ai/issues/731
- [ ] https://github.com/microsoft/teams-ai/issues/784
- [ ] https://github.com/microsoft/teams-ai/issues/290
- [ ] https://github.com/microsoft/teams-ai/issues/239
- [ ] https://github.com/microsoft/teams-ai/issues/493
- [ ] https://github.com/microsoft/teams-ai/issues/1009
- [ ] https://github.com/microsoft/teams-ai/issues/1055
- [ ] https://github.com/microsoft/teams-ai/issues/1057
- [ ] https://github.com/microsoft/teams-ai/issues/1179
```

**Comment by corinagum** [comment]
Closing since all items are complete
