### ISSUE TITLE
[PY] Support all Teams activity handlers

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1131]
### Scenario

JS / C# has feature to support all activity handlers. Here's related feature for JS: https://github.com/microsoft/teams-ai/issues/194. Python might need to do the same thing. Creating this issue to discuss.

### Solution

Support all activity handlers like JS / C#.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1292
- [ ] https://github.com/microsoft/teams-ai/issues/1293
- [ ] https://github.com/microsoft/teams-ai/issues/1296
- [ ] https://github.com/microsoft/teams-ai/issues/1297
- [ ] https://github.com/microsoft/teams-ai/issues/1301
```

**Comment by blackchoey** [comment]
Moving to triaged as this has been discussed in last week's scrum
