### ISSUE TITLE
[PY] Update and add new samples for breaking changes

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1175]
- Also includes update the README to ensure setup is consistent across JS/C#/Python

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1323
- [ ] https://github.com/microsoft/teams-ai/issues/1254
- [ ] https://github.com/microsoft/teams-ai/issues/312
- [ ] https://github.com/microsoft/teams-ai/issues/1263
- [ ] https://github.com/microsoft/teams-ai/issues/318
- [ ] https://github.com/microsoft/teams-ai/issues/672
```

-
