### ISSUE TITLE
[Samples cleanup]: Updated Code for Teams ToolKit "Create an AI Chatbot" template with Teams AI Library & Updated/More Samples

### ISSUE THREAD

**Issue by Carter425** [microsoft/teams-ai#1250]
### Scenario

The "Create an AI Chatbot" template with Teams AI Library on the Teams Toolkit is out of date compared to the Teams AI Library newer code. For example, Teams Toolkit users still have to uncomment Azure OpenAI planner in index.ts prior to using Azure OpenAI Service with the Teams AI Library. This is an inconsistent and more complicated experience than the newer version of the Teams AI Library. Second, C# can be added as a language option to create an AI Chat Bot. Last, there can be more samples from the Teams AI Library on Teams Toolkit.

1 Pager Spec for additional details
https://microsoft-my.sharepoint.com/:w:/p/v-cgilliam/EQvZryU1xiJErTXNih07APIBOkiISejtMWlzOmfw_5YZrg?e=KbbNGN

David Rousset and Junjie Li created this bug on the Teams Toolkit side to track on their end https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26687860

### Solution

Provide the updated code for the Teams AI Library to the Teams Toolkit team in JavaScript, Typescript, & #C in order to update the "Create an AI Chatbot" template in Teams Toolkit. 

Additionally, assist in the coordination of sending over chosen samples to Teams Toolkit

### Additional Context

Example of out of date code.
![image](https://github.com/microsoft/teams-ai/assets/146026801/99965111-f85b-4d96-b718-2c05ee2a69ad)

=====

@corinagum section

```[tasklist]
### Tasks
- [ ] Reorganize samples directory
- [ ] Update samples/README.md and SAMPLES.md (especially links)
- [ ] https://github.com/microsoft/teams-ai/issues/954
- [ ] https://github.com/microsoft/teams-ai/issues/1461
- [ ] https://github.com/microsoft/teams-ai/pull/1458
- [ ] https://github.com/microsoft/teams-ai/issues/1439
- [x] Add section about how provisioned bots need to be outside of teams-ai directory
- [ ] https://github.com/microsoft/teams-ai/issues/1428
- [ ] https://github.com/microsoft/teams-ai/issues/1427
- [ ] https://github.com/microsoft/teams-ai/issues/1405
```
