### ISSUE TITLE
[PY] GA Samples

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#1333]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1261
- [ ] https://github.com/microsoft/teams-ai/issues/1252
- [ ] https://github.com/microsoft/teams-ai/issues/314
- [ ] https://github.com/microsoft/teams-ai/issues/1253
- [ ] https://github.com/microsoft/teams-ai/issues/309
- [ ] https://github.com/microsoft/teams-ai/issues/315
- [ ] https://github.com/microsoft/teams-ai/issues/316
```
