### ISSUE TITLE
Azure AI Search Data Source epic

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1359]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1738
- [ ] https://github.com/microsoft/teams-ai/issues/1739
- [ ] https://github.com/microsoft/teams-ai/issues/1360
- [ ] https://github.com/microsoft/teams-ai/issues/1410
- [ ] https://github.com/microsoft/teams-ai/issues/1419
- [ ] https://github.com/microsoft/teams-ai/issues/1442
- [ ] https://github.com/microsoft/teams-ai/issues/1730
```
