### ISSUE TITLE
Streaming epic

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1492]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1968
- [ ] https://github.com/microsoft/teams-ai/issues/1969
- [ ] https://github.com/microsoft/teams-ai/issues/1964
- [ ] https://github.com/microsoft/teams-ai/issues/1920
- [ ] https://github.com/microsoft/teams-ai/issues/1593
- [ ] https://github.com/microsoft/teams-ai/issues/2036
- [ ] https://github.com/microsoft/teams-ai/issues/1540
- [ ] https://github.com/microsoft/teams-ai/issues/1967
- [ ] https://github.com/microsoft/teams-ai/issues/1970
- [ ] https://github.com/microsoft/teams-ai/issues/2098
- [ ] https://github.com/microsoft/teams-ai/issues/2162
```
