### ISSUE TITLE
[Feat]: add support for AI assistants=v2 version API

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/teams-ai#1585]
### Language

Javascript/Typescript

### Version

latest

### Description

It appears that users cannot change the OpenAI assistant's API version, as Teams AI is currently utilizing version 4.28.4 of the OpenAI npm package, with its assistant's API version set to v1. Will you update this OpenAI npm package to the latest version, or how can we change the assistant's API version?

![image](https://github.com/microsoft/teams-ai/assets/13211513/7df236c3-584c-41dc-8b96-7b4d3145098c)

Related bug: https://github.com/OfficeDev/TeamsFx/issues/11512

### Reproduction Steps

```bash
...
```

```[tasklist]
### Tasks
- [x] C#
- [ ] PY
- [ ] JS v2 work
- [ ] JS - Remove `@azure/openai` dependency from AssistantsPlanner
- [ ] JS/PY - verify sample 4.h isn't broken
- [ ] JS/PY- Assistants citations https://github.com/microsoft/teams-ai/issues/1590
- [ ] All - Assistants managed identity auth https://github.com/microsoft/teams-ai/issues/1918
- [ ] All - Verify gpt-4o and 4o-mini https://github.com/microsoft/teams-ai/issues/1861
```

**Comment by Valentinoaa** [comment]
Hi, I´m facing the same issue, but you don´t have to change the v1 in the endpoint, just change the header, check the OpenAI documentation:
![image](https://github.com/microsoft/teams-ai/assets/81339785/ccd62ad8-d7d3-4035-9a05-5271c727ccd2)


> OpenAI Assistant API version is hard-coded in a few files. I am using Microsoft Visual Studio. For example, this C# file also has v1 hard-coded in the threads API endpoint -> teams-ai/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.Thread.cs ![OpenAIThreadAPIversionhardcoded](https://private-user-images.githubusercontent.com/168040747/327614477-e76f83e6-deb2-4b8d-bd01-5098ba2b2196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjIzMjcsIm5iZiI6MTcxNTI2MjAyNywicGF0aCI6Ii8xNjgwNDA3NDcvMzI3NjE0NDc3LWU3NmY4M2U2LWRlYjItNGI4ZC1iZDAxLTUwOThiYTJiMjE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzQ2ZWZmNTQ0ZTkyODg3ZDVjYjAzZDUyYjYzOWNiMDE2ZjRhZTExZDIyYmNmYTI4YmJhZTFlOWY0ZWM0MWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PMEkcD4yHo2wwtCAnF1BI1upjNDsjAqJhs0gz-iTELM)

**Comment by smithcal1000** [comment]
@Valentinoaa Thank you, but how can you change the version number in the header when using the Teams AI Library provided by Microsoft to create an AI assistant bot [Preview] Teams app in Microsoft Visual Studio or VS Code?

**Comment by Valentinoaa** [comment]
@smithcal1000, you´re wellcome.
I´ve pulled and example from the TeamsAI repo in Python and I´ve fixed it installing the latest OpenAI version (running `pip install openai=1.27.00`), maybe you´ll have to modify some lines (including the Poetry dependencies). You can check how to migrate [here](https://platform.openai.com/docs/assistants/migration/what-has-changed).

**Comment by smithcal1000** [comment]
I just checked and Microsoft has not yet released the Azure.AI.OpenAI.Assistants package that supports streaming and Assistants v2. It says it will be coming soon in a future update.

**Comment by Valentinoaa** [comment]
> I just checked and Microsoft has not yet released the Azure.AI.OpenAI.Assistants package that supports streaming and Assistants v2. It says it will be coming soon in a future update.

Check [this](https://github.com/microsoft/teams-ai/tree/main/python/samples/06.assistants.b.orderBot) example. I´m using it and it works well. You just have to migrate manually to the latest OpenAI SDK as I mentioned before.

**Comment by ahmedmahmoudR** [comment]
> > I just checked and Microsoft has not yet released the Azure.AI.OpenAI.Assistants package that supports streaming and Assistants v2. It says it will be coming soon in a future update.
> 
> Check [this](https://github.com/microsoft/teams-ai/tree/main/python/samples/06.assistants.b.orderBot) example. I´m using it and it works well. You just have to migrate manually to the latest OpenAI SDK as I mentioned before.

I tried your solution, and it works after I manually installed the latest OpenAI SDK. However, can I do the same with JS instead of Python?

**Comment by stuart-pebble** [comment]
Did you manage to get this working with JavaScript? 

And if so did you need to modified any code / headers etc?

**Comment by corinagum** [comment]
Since assistants in OpenAI are still beta, this feature request is in our backlog and not being prioritized at the moment. Please feel free to share here any code as workarounds for others to take advantage of :)

**Comment by stuart-pebble** [comment]
The objective of the update is to update the API calls to the OpenAI Assistant to V2 in the hope that this would then have the interactions with the Assistant use its local vector store for context. It currently “works” for chat but is useless without the context. Nearly brilliant.

I’ve investigated making the updates to teams-ai myself but its beyond my skill levels, even with an arm of AI tools. I might be able to butcher it but it would likely break everything else and not aligned with the teams-ai objectives.

For now, I’ll have to use an alternative to Teams keep an eye on the project and circle back when support is added. I’ll be happy to beta test something when its available.

Thanks for driving the project, I really think Teams is a great way to enable AI adoption by bringing AI to where users work everyday.

From: Corina ***@***.***>
Date: Wednesday, 24 July 2024 at 4:40 AM
To: microsoft/teams-ai ***@***.***>
Cc: Stuart Hirst ***@***.***>, Comment ***@***.***>
Subject: Re: [microsoft/teams-ai] [Feat]: add support for AI assistants=v2 version API (Issue #1585)

Since assistants in OpenAI are still beta, this feature request is in our backlog and not being prioritized at the moment. Please feel free to share here any code as workarounds for others to take advantage of :)

**Comment by singhk97** [comment]
#1914 #1915

**Comment by singhk97** [comment]
Python & C# have been updated to support leaving only JS that needs to be brought to parity.

**Comment by stuart-pebble** [comment]
Looking like good progress. Just an FYI that when using the VSCode MS Teams Toolkit, the only options when choosing "Build with Assistants API" is JavaScript and TypeScript. Looking forward to the JS updates :-)

**Comment by stuart-pebble** [comment]
Any progress with JS support?

**Comment by singhk97** [comment]
Summarizing support in the C# SDK:
* `AssistantsPlanner` uses `beta-v2` by default.
* File upload & download support
  * PR: https://github.com/microsoft/teams-ai/pull/1945
  * Issue: https://github.com/microsoft/teams-ai/issues/1919
* Authentication using Managed Identity
   * PR: https://github.com/microsoft/teams-ai/pull/1930
   * Issue: https://github.com/microsoft/teams-ai/issues/1918
* File search tool support
   * PR: https://github.com/microsoft/teams-ai/pull/1913/files
   * Issue: https://github.com/microsoft/teams-ai/issues/1590
