### ISSUE TITLE
[JS] Support ALL teamsActivityHandlers

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#194]
## List of non-implemented handlers as of July 11

(If Tatiana's team adds more, we will need to add to this list)

from `botbuilder-js/libraries/botbuilder/src/teamsActivityHandler.ts`

- Adaptive Cards - unit tests
- Meeting events

### Message Extension events
- [x] 'config/fetch' (auth or task)
- [x] 'config/submit' (auth or task)
- [x] 'fileConsent/invoke' (accept/decline)
- [x] 'actionableMessage/executeAction'
- [x] 'composeExtension/querySettingUrl' 
- [x] 'composeExtension/setting'
- [x] 'composeExtension/onCardButtonClicked'

### Task modules events
- [x] 'task/fetch'
- [x] 'task/submit'

### Conversation update events
- [x] 'teamHardDeleted'
- [x] 'teamUnarchived'

### Message update
- [x] 'undeleteMessage'
- [x] 'editMessage'

### Message Delete
- [x] 'softDeleteMessage'

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/248
- [ ] https://github.com/microsoft/teams-ai/issues/246
- [ ] https://github.com/microsoft/teams-ai/issues/249
- [ ] https://github.com/microsoft/teams-ai/issues/247
- [ ] https://github.com/microsoft/teams-ai/issues/770
- [ ] https://github.com/microsoft/teams-ai/issues/243
- [ ] https://github.com/microsoft/teams-ai/issues/245
- [ ] https://github.com/microsoft/teams-ai/issues/668
```

**Comment by singhk97** [comment]
![image](https://github.com/microsoft/teams-ai/assets/115390646/1be6ce8c-97f6-4513-992c-088d991e1a36)
![image](https://github.com/microsoft/teams-ai/assets/115390646/951487e1-53f3-468f-a0b0-b2bd033df894)

Meetings related scenarios

**Comment by corinagum** [comment]
Complete, not including unit tests
