### ISSUE TITLE
[C# Port] Samples

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#211]
- [x] 01.messaging.a.echoBot
- [x] 02.messageExtensions.a.searchCommand
- [x] 03.adaptiveCards.a.typeAheadBot
- [x] ~Custom TurnState classes~
- [x] 04.ai.a.teamsChefBot
- [x] 04.ai.b.messageExtensions.gptME
- [x] 04.ai.c.actionMapping.lightBot
- [x] 04.ai.d.chainedActions.listBot
- [x] 04.ai.e.chainedActions.devOpsBot
- [x] 04.e.twentyQuestions
- [ ] 04.q.questBot
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/234
- [ ] https://github.com/microsoft/teams-ai/issues/250
- [ ] https://github.com/microsoft/teams-ai/issues/251
- [ ] https://github.com/microsoft/teams-ai/issues/242
- [ ] https://github.com/microsoft/teams-ai/issues/255
- [ ] https://github.com/microsoft/teams-ai/issues/292
- [ ] https://github.com/microsoft/teams-ai/issues/293
- [ ] https://github.com/microsoft/teams-ai/issues/294
- [ ] https://github.com/microsoft/teams-ai/issues/367
```

**Comment by corinagum** [comment]
Prioritize 
- teamsChefBot
- listBot
- twentyQuestions

**Comment by corinagum** [comment]
ME / ME GPT - Qianhao
typeahead Kuojian
ListBot - Kavin
