### ISSUE TITLE
Python Botbuilder Parity epic

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#216]
This epic covers all the tasks and sub-epics needed to achieve feature parity in Python SDK. Completing this epic means that Python SDK will have the same features as JS SDK.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/240
- [ ] https://github.com/microsoft/teams-ai/issues/340
- [ ] https://github.com/microsoft/teams-ai/issues/341
- [ ] https://github.com/microsoft/teams-ai/issues/342
- [ ] https://github.com/microsoft/teams-ai/issues/343
- [ ] https://github.com/microsoft/teams-ai/issues/344
- [ ] https://github.com/microsoft/teams-ai/issues/345
- [ ] https://github.com/microsoft/teams-ai/issues/346
- [ ] https://github.com/microsoft/teams-ai/issues/347
- [ ] https://github.com/microsoft/teams-ai/issues/348
- [ ] https://github.com/microsoft/teams-ai/issues/349
- [ ] https://github.com/microsoft/teams-ai/issues/350
- [ ] https://github.com/microsoft/teams-ai/issues/351
- [ ] https://github.com/microsoft/teams-ai/issues/352
- [ ] https://github.com/microsoft/teams-ai/issues/353
- [ ] https://github.com/microsoft/teams-ai/issues/354
- [ ] https://github.com/microsoft/teams-ai/issues/355
- [ ] https://github.com/microsoft/teams-ai/issues/1300
```
