### ISSUE TITLE
Identify New Features Needed For Parity

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#240]
Using the Bot Builder Dotnet Repository (as it is the source of truth for botbuilder parity), identify feature gaps between the Botbuilder Dotnet and Python SDK's.

If it is found that any of these tasks are already present in the Python SDK they can be closed out.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/340
- [ ] https://github.com/microsoft/teams-ai/issues/341
- [ ] https://github.com/microsoft/teams-ai/issues/342
- [ ] https://github.com/microsoft/teams-ai/issues/343
- [ ] https://github.com/microsoft/teams-ai/issues/344
- [ ] https://github.com/microsoft/teams-ai/issues/345
- [ ] https://github.com/microsoft/teams-ai/issues/346
- [ ] https://github.com/microsoft/teams-ai/issues/347
- [ ] https://github.com/microsoft/teams-ai/issues/348
- [ ] https://github.com/microsoft/teams-ai/issues/349
- [ ] https://github.com/microsoft/teams-ai/issues/350
- [ ] https://github.com/microsoft/teams-ai/issues/351
- [ ] https://github.com/microsoft/teams-ai/issues/352
- [ ] https://github.com/microsoft/teams-ai/issues/353
- [ ] https://github.com/microsoft/teams-ai/issues/354
- [ ] https://github.com/microsoft/teams-ai/issues/355
```

**Comment by aacebo** [comment]
Update: Tracy Boehrer `would estimate that we haven't made any Teams updates to Python since at earliest last October.  Possibly longer than that.`

**Comment by aacebo** [comment]
@blackchoey I think the best way to split up efforts right now is for one of use to work on adding these features to the Python Bot Builder https://github.com/microsoft/botbuilder-python and the other to work on porting the AI SDK. Which task would you prefer doing?

**Comment by blackchoey** [comment]
@aacebo Thank you. I would prefer to continue working on the AI SDK part because I focused on this for some time. And you might be more familiar with these Bot Builder features you figured out. What do you think about this?
