### ISSUE TITLE
[C#] Code Review

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#252]
We want to do a code review before public preview. Ideally we should incorporate feedback from .NET team expert Stephen Toub:

- [X] A check mark is placed if a work item is created for the feedback, or it has been addressed.

Here's the feedback from Stephen Toub regarding the current state of the C# SDK:

- [x] It’s not at all clear how to get started. I see Microsoft.Bot as a namespace, but it’s got five nested namespaces, and the first one I look at (Builder) has a ton of types. What is the expectation for how someone new to this navigates the system? Is the expectation that someone follows a sample or a getting-started doc somewhere? Otherwise, it’s not intuitive how to even get going. 
  - Response: [Getting Started docs](https://github.com/microsoft/teams-ai/tree/main/getting-started)

- [X] - From a development perspective, ideally there’d be some template where I could just say “New Bot”, it would scaffold the project for me, and if I F5’d, it’d set up everything so I could immediately start debugging and trying out my bot with Teams. Is that the intent and it’s just not there yet? The samples readme should have the instructions for the F5 experience to get the bot started. 
  - Response: [Samples](https://github.com/microsoft/teams-ai/tree/main/dotnet/samples)

- [x] - What are AIException / PlannerException / ResponseParserException / PromptManagerException / AzureContentSafeyClientException, and why do they need to exist / be public? Do you have examples where code needs to catch these exceptions specifically and do something with them that they don’t do with other exceptions? They’re not storing / communicating any other state that someone could consume. (Have a conversation with Steve & Alex to find a common ground)
	- [x] Response: Removed all these exceptions. Replaced with 2 custom exceptions, `TeamsAIException` being the generic exception, and `HttpOperationException` which is thrown when an api call returns a failure status code.
- [X] - Does TypingTimer need to be public? What’s the use case for that? Naively that seems like an implementation detail of other components in the library. What is the public TurnStateEntry? It’s just an empty class. Same for TurnStateManager, TurnState, etc. Why do they exist / why are they public? Are they somehow just used for their object identities?
  - Response: A public TypingTimer allows users to use it independent of the `Application` class's default use case. When Stephen had reviewed them the turn state classes were empty stubs. The turn state class encapsulates data and methods to make a cookie-like data structure. The turn state manager handles loading/saving the turn state data to storage. The storage is configurable by the user, and it's a class from the botframework SDK. The ones used in the samples are the memory storage class, which simply stores the data to the .NET applications memory.

- [X] - Application.AI throws the base Exception type. That’s not desirable. It should be InvalidOperationException in this case. But it’d be even better if it didn’t throw. Why not just make the property be e.g. public AI<TState>? AI => _ai;, having it return null if the instance isn’t available?
  -  Response:  We expect end users to to access the AI class using this property. Whether it is null or not, is solely based on the end user's configuration of the Application class, through the ApplicationOptions class. If a user accesses this property, and it doesn't exist, it is because the they failed to configure it. Throwing an exception is a way to notify them of this.

- [x] - Why do the base OnMessage*ActivityAsync methods throw a NotImplementedException rather than just being a nop? That seems very unexpected, and also then forces the caller to catch NotImplementedException, which is equally strange. 
	- [x] Response: We will be phasing out this activting handler system and implementing a fluent api-like public api (think: Asp.Net Minimal APIs)

- [x] - ResponseParser is public. Is that something you expect consuming code to use? I’d urge you to keep things internal/private unless you have a demonstrated need for them to be consumed externally. If you do keep it public, it should also be static. And it would benefit from a better name. “Response” from what? 
	- [x] Response: Made it internal

- [x] - Also, I see Newtonsoft JSON is being used. Can you switch to using System.Text.Json?
	- [x] Response: Switched it over to System.Text.Json except code that was dependent to  the Bot Framework SDK because it is coupled with their internal library code.

- [x] - AITypes isn’t sealed or static, so folks can end up deriving from it. It also has “Types” in its name, but the whole class contains just three constant strings, which are more commands than anything else. Does this need to be exposed at all? Is there a better place to put these constants? (Conversation with Alex & Steve)
	- [x] Response: Renamed it to `AIConstants` and it now holds all constants used in the AI system.

- [x] - You can simplify your use of Verify.NotNull by putting a [CallerArgumentExpression] on the second parameter, e.g. [https://github.com/microsoft/semantic-kernel/blob/65beb75f62ad60899b413676acd760bfaa4a90b3/dotnet/src/InternalUtilities/src/Diagnostics/Verify.cs#L22](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fsemantic-kernel%2Fblob%2F65beb75f62ad60899b413676acd760bfaa4a90b3%2Fdotnet%2Fsrc%2FInternalUtilities%2Fsrc%2FDiagnostics%2FVerify.cs%23L22&data=05%7C01%7Ckavinsingh%40microsoft.com%7Caea772aa8ca6440be59008db7d9e4620%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638241890965010732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YwmYT37Ltsn7VX70OD1hG4jjHUVehrvcmXefzV4e0wI%3D&reserved=0). Since you’re targeting netstandard2.0, you can just copy that attribute into your assembly as internal. 
	- [x] Response: Implemented

- [x] - For AIHistoryOptions, what happens if someone sets an invalid value into one of the properties? There’s currently no validation happening. Should there be validation in the setters? Or do you allow for garbage data here and then validate it when it’s actually used?
	- [x] Response: We trust the end user to not provide nonsensical inputs. (Ex. -1 to max # recent conversation history to persist)

- [x] - You’re trying to hide SK, but there are methods like CreateSemanticFunction, using terminology from SK. Is that desirable?
	- [x] Response: Yes that's to differentiate from a native function.

- [x] - ActionAttribute should be sealed. Its properties should also be get-only. (Make the changes unless good reason not to)
	- [x] Response: done.

- [x] - What is the expectation for how DefaultActions is used? I see a new instance of it is imported by the AI constructor… is it then just an implementation detail and can be internal? 
  - Response: Made this class internal

- [x] - AzureContentSafetyClient should use a singleton HttpClient instance if no HttpClient is provided. And it should Dispose of any clients it creates, which means AzureContentSafetyClient should be IDisposable, which also means you probably want to seal it or you’re going to want to implement the more full-fledged IDisposable pattern.  
- [x] - ExecuteTextModeration is creating a new JsonSerializerOptions on every call… this is super expensive, especially pre-.NET 7. It should cache a singleton JsonSerializerOptions instance and use that over and over. (Investigate codebase and implement fix)
- [x] - Same property validation question I asked earlier goes for other types as well, like AzureContentSafetyClientOptions.
- [x] There’s no Azure SDK for content safety? Shipping all of these AzureContentSafety-related client types in the Teams AI bot SDK does not seem like the right place. I’d instead expect this SDK to be pulling in some nuget package for that support if it were needed. And at a minimum I wouldn’t expect it to be public here. (Talk to Steve and Alex)
- [x] - Why is a public OpenAI client needed here? If the expectation is consumers of this SDK interact with OpenAI directly, why can’t they use the official client SDKs? Response: Official client SDK does not have the Moderation API included. We are in contact with the official msft open ai sdk, requesting them to include this api in their sdk.
- [x] Same for AzureOpenAI. (Investigate why it's public, and if possible make it private/internal) Response: Using external Azure SDK insteading of implementing our own client..
- [x] - Do the custom JsonConverters need to be public? (No they don't, we can make the fix).
- [x] - I think it’s unfortunate that this is creating a whole new set of types around plans / prompt management / native functions / semantic functions / orchestration / etc. It’d be really nice IMHO if this could instead just leverage Semantic Kernel. Have you spoken to the SK team recently? Have you thought through what it would look like to have a larger SK dependency? I do appreciate the goal of trying to not tie this to SK, but at the same time, it’s now creating a secondary framework for interacting with AI. What happens when someone wants to use a vector database with their teams AI bot? Are you going to create abstractions and implementations for all of those? What happens when someone wants to import the native and semantic functions for SK for use in their teams bot? 
	- [x] Response: Steve is currently tweaking the architecture so that a developer can use an "SKPlanner" or "LangChanPlanner" with the Teams AI SDK itself.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/406
- [ ] https://github.com/microsoft/teams-ai/issues/407
- [ ] https://github.com/microsoft/teams-ai/issues/408
- [ ] https://github.com/microsoft/teams-ai/issues/414
- [ ] https://github.com/microsoft/teams-ai/issues/415
- [ ] https://github.com/microsoft/teams-ai/issues/416
- [ ] https://github.com/microsoft/teams-ai/issues/417
