### ISSUE TITLE
C# SDK private preview epic

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#253]
We'll track all the outstanding post-port C# SDK work items in this issue.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/254
- [ ] https://github.com/microsoft/teams-ai/issues/256
- [ ] https://github.com/microsoft/teams-ai/issues/255
- [ ] https://github.com/microsoft/teams-ai/issues/211
```

**Comment by corinagum** [comment]
Closing as complete :)
