### ISSUE TITLE
C# SDK public preview epic

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#257]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/252
- [ ] https://github.com/microsoft/teams-ai/issues/258
- [ ] https://github.com/microsoft/teams-ai/issues/82
- [ ] https://github.com/microsoft/teams-ai/issues/253
- [ ] https://github.com/microsoft/teams-ai/issues/404
- [ ] https://github.com/microsoft/teams-ai/issues/443
- [ ] https://github.com/microsoft/teams-ai/issues/502
- [ ] https://github.com/microsoft/teams-ai/issues/532
- [ ] https://github.com/microsoft/teams-ai/issues/589
- [x] https://github.com/microsoft/teams-ai/issues/619
```

**Comment by corinagum** [comment]
Should include feedback from Stephen
