### ISSUE TITLE
[PY] Samples

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#300]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/308
- [ ] https://github.com/microsoft/teams-ai/issues/310
- [ ] https://github.com/microsoft/teams-ai/issues/311
- [ ] https://github.com/microsoft/teams-ai/issues/313
- [ ] https://github.com/microsoft/teams-ai/issues/317
- [ ] https://github.com/microsoft/teams-ai/issues/1175
- [ ] TBD
```

**Comment by corinagum** [comment]
Closing as complete!
