### ISSUE TITLE
Python SDK high level design spec

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#305]
This task aims to identify below high level design details for Python SDK. We could then have break down tasks for each SDK feature design.
```[tasklist]
### Tasks
- [x] Python version to support
- [x] Proposed package name
- [x] Inherit bot framework or have more Pythonic interface
- [x] Feature list and why we need these features
- [x] Example dev experience of Python SDK
- [x] Review follow up: sync with Kavin on attribute problems in dotnet
```
