### ISSUE TITLE
Python SDK basic functionality epic

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#384]
My proposal definition for basic functionality is: users are able to build the `teamsChefBot` sample using the Python SDK. Moderation related features can be out of scope as it does not block the main path.

This milestone contains following features:
1. Out-of-box conversation / user / temp state
2. OpenAI and AzureOpenAI planner
3. Prompt template engine built into OpenAI/AzureOpenAI planner
4. AI class that calls planner and executes plan (first supports `SAY` action)
5. Register activity handler to the application
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/385
- [ ] https://github.com/microsoft/teams-ai/issues/386
- [ ] https://github.com/microsoft/teams-ai/issues/387
- [ ] https://github.com/microsoft/teams-ai/issues/388
- [ ] https://github.com/microsoft/teams-ai/issues/389
- [ ] https://github.com/microsoft/teams-ai/issues/390
- [ ] https://github.com/microsoft/teams-ai/issues/448
- [ ] https://github.com/microsoft/teams-ai/issues/451
- [ ] https://github.com/microsoft/teams-ai/issues/455
- [ ] https://github.com/microsoft/teams-ai/issues/456
- [ ] https://github.com/microsoft/teams-ai/issues/457
- [ ] https://github.com/microsoft/teams-ai/issues/458
- [ ] https://github.com/microsoft/teams-ai/issues/304
- [ ] https://github.com/microsoft/teams-ai/issues/509
- [ ] https://github.com/microsoft/teams-ai/issues/499
- [ ] https://github.com/microsoft/teams-ai/issues/444
- [ ] https://github.com/microsoft/teams-ai/issues/307
- [ ] https://github.com/microsoft/teams-ai/issues/265
```
