### ISSUE TITLE
Python SDK private preview epic

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#396]
The proposed scope for private preview is Python SDK reaches same feature parity as **JS SDK** and can be dogfooded by some partners. P0 scenarios should be well tested for private preview SDK.

This milestone contains following features:
1. Wrapper to register handlers for common bot events

    1. Bot messages
    1. Message Extension
    1. Adaptive Card
    1. Task Module
   
1. Moderator to review user input and prompts
1. Hero samples (not all the samples as we have in JS) to illustrate the usage of Teams-AI Python SDK

Below are open questions to Python SDK:
1. Since Python botbuilder is being deprecated, should the private preview version still reference the deprecated package, or we need to figure out additional solution?

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/447
- [ ] https://github.com/microsoft/teams-ai/issues/446
- [ ] https://github.com/microsoft/teams-ai/issues/432
- [ ] https://github.com/microsoft/teams-ai/issues/498
- [ ] https://github.com/microsoft/teams-ai/issues/518
- [ ] https://github.com/microsoft/teams-ai/issues/471
- [x] Whether to depend on Python botbuilder in private preview - We are no longer unifying
- [ ] https://github.com/microsoft/teams-ai/issues/445
- [ ] https://github.com/microsoft/teams-ai/issues/534
- [ ] https://github.com/microsoft/teams-ai/issues/564
- [ ] https://github.com/microsoft/teams-ai/issues/565
- [ ] https://github.com/microsoft/teams-ai/issues/612
- [ ] https://github.com/microsoft/teams-ai/issues/656
```

**Comment by blackchoey** [comment]
@aacebo moved some tasks to public preview per our offline sync. Feel free to update this epic if anything is out of date.

**Comment by aaronsaikovski-tl** [comment]
how can we get on the Python SDK beta?

**Comment by aacebo** [comment]
> how can we get on the Python SDK beta?

First we will be doing a "Private Preview" which is an interview company preview so we can test and make any last breaking changes. Then we will publish an `alpha` package with our "Public Preview" soon after that, which is being tracked by https://github.com/microsoft/teams-ai/issues/397.

The public preview alpha will be publicly available via PYPI.
