### ISSUE TITLE
Python Public Preview

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#397]
The proposed scope for public preview mainly focus on the document and example part. To help developers better get started and learn how to build apps with the SDK.
In the meanwhile, feedbacks from private preview is another key thing to resolve in public preview.

Some open questions to this milestone:
1. Semantic Kernel mentions it's going to [refactor](https://learn.microsoft.com/en-us/semantic-kernel/get-started/supported-languages#notes-about-the-python-sdk) its Python SDK. Since our SDK is built upon SK, we need to align with them on this (mainly about breaking changes) and determine the timeline.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1064
- [ ] https://github.com/microsoft/teams-ai/issues/324
- [ ] https://github.com/microsoft/teams-ai/issues/298
- [ ] https://github.com/microsoft/teams-ai/issues/682
- [ ] https://github.com/microsoft/teams-ai/issues/1066
- [ ] https://github.com/microsoft/teams-ai/issues/1067
- [ ] https://github.com/microsoft/teams-ai/issues/1072
- [ ] https://github.com/microsoft/teams-ai/issues/1079
- [ ] https://github.com/microsoft/teams-ai/issues/1070
- [ ] https://github.com/microsoft/teams-ai/issues/1068
- [ ] https://github.com/microsoft/teams-ai/issues/1065
- [ ] https://github.com/microsoft/teams-ai/issues/768
- [ ] https://github.com/microsoft/teams-ai/issues/1073
- [ ] https://github.com/microsoft/teams-ai/issues/1069
- [ ] https://github.com/microsoft/teams-ai/issues/1283
- [ ] https://github.com/microsoft/teams-ai/issues/1131
- [ ] https://github.com/microsoft/teams-ai/issues/1071
- [ ] https://github.com/microsoft/teams-ai/issues/1286
- [ ] https://github.com/microsoft/teams-ai/issues/1164
- [ ] https://github.com/microsoft/teams-ai/issues/1248
- [ ] https://github.com/microsoft/teams-ai/issues/1175
- [ ] https://github.com/microsoft/teams-ai/issues/299
- [ ] https://github.com/microsoft/teams-ai/issues/566
- [ ] https://github.com/microsoft/teams-ai/issues/1383
```

**Comment by blackchoey** [comment]
Add https://github.com/microsoft/teams-ai/issues/1131 as discussed in scrum, low priority.

**Comment by lilyydu** [comment]
Completed.
