### ISSUE TITLE
Revamp exception classes in C# SDK

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#485]
What are AIException / PlannerException / ResponseParserException / PromptManagerException / AzureContentSafeyClientException, and why do they need to exist / be public? Do you have examples where code needs to catch these exceptions specifically and do something with them that they don’t do with other exceptions? They’re not storing / communicating any other state that someone could consume
```[tasklist]
### Tasks
- [x] Remove various exception classes that don't communicate any values up the stack. Create a generic "TeamsAIException"
- [x] Create an exception class for all AI related exceptions
- [x] Issue: The end user has no way of knowing when a call is rated limited.
```
