### ISSUE TITLE
C# SDK GA Epic

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#533]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/569
- [ ] https://github.com/microsoft/teams-ai/issues/759
- [ ] https://github.com/microsoft/teams-ai/issues/714
- [ ] https://github.com/microsoft/teams-ai/issues/843
- [ ] https://github.com/microsoft/teams-ai/issues/905
- [ ] https://github.com/microsoft/teams-ai/issues/803
- [ ] https://github.com/microsoft/teams-ai/issues/915
- [ ] https://github.com/microsoft/teams-ai/issues/936
- [ ] https://github.com/microsoft/teams-ai/issues/949
- [ ] https://github.com/microsoft/teams-ai/issues/959
- [ ] https://github.com/microsoft/teams-ai/issues/788
- [ ] https://github.com/microsoft/teams-ai/issues/735
- [ ] https://github.com/microsoft/teams-ai/issues/268
- [ ] https://github.com/microsoft/teams-ai/issues/405
- [ ] https://github.com/microsoft/teams-ai/issues/989
- [ ] https://github.com/microsoft/teams-ai/issues/993
- [ ] https://github.com/microsoft/teams-ai/issues/1022
- [ ] https://github.com/microsoft/teams-ai/issues/1025
- [ ] https://github.com/microsoft/teams-ai/issues/1028
- [ ] https://github.com/microsoft/teams-ai/issues/737
```
