### ISSUE TITLE
[JS] Unit tests

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#54]
%age goal?
This will also depend on when we believe breaking changes will settle down

12/7 list of JS unit tests BELOW 80%

```[tasklist]
### Tasks
- [ ] AI.ts - 🐙 Corina
- [ ] Application.ts - 🐙 Corina
- [x] TeamsAttachmentDownloader.ts - 🐙 Corina (I have to investigate a bug in this anyway)
- [ ] TurnState.ts
- [ ] TurnStateProperty.ts
- [ ] OpenAIEmbeddings.ts
- [x] TestEmbeddings.ts - 🐙 Corina (reorganize)
- [x] Colorize.ts
- [ ] OpenAIModel.ts
- [ ] ActionPlanner.ts
- [ ] AssistantsPlanner.ts
- [ ] LLMClient.ts
- [x] TestPlanner.ts - 🐙 Corina (reorganize)
- [ ] PromptManager.ts
- [x] TestPromptManager.ts - 🐙 Corina (reorganize)
- [x] UserInputMessage.ts
- [x] ~TeamsSsoAdaptiveCardAuthentication.ts~ - 😈 Kavin (Not applicable since it's an internal class stub)
- [x] TaskModules.ts - 🐙 Corina
- [x] Authentication.ts - 😈  Kavin
- [x] OAuthBotAuthentication.ts - 😈 Kavin
- [x] UserTokenAccess.ts - 🌱 Lily
- [x] AzureOpenAIClient.ts - 🌱 Lily
- [x] OpenAIClient.ts - 🌱 Lily
- [ ] https://github.com/microsoft/teams-ai/issues/1052
- [x] AzureContentSafetyModerator.ts - 🌱 Lily
- [x] TextDataSource.ts - 🐙 Corina
- [x] OpenAIModerator.ts - 🌱 Lily
- [x] AdaptiveCards.ts - 😈 Kavin
- [x] DataSourceSection.ts - 🌱 Lily
- [x] FunctionCallMessage.ts -🌱 Lily
- [x] FunctionResponseMessage.ts - 🌱 Lily
- [x] SequenceAugmentation.ts -  🌱 Lily
- [x] OAuthAdaptiveCardAuthentication.ts - 😈 Kavin
- [x] DefaultAugmentation.ts - 🌱 Lily
- [x] JSONResponseValidator.ts - 🐙 Corina
```

**Comment by corinagum** [comment]
80% goal

**Comment by corinagum** [comment]
Closing this as out of date. Will open new items for remaining files that need coverage.
