### ISSUE TITLE
[PY] Publish package

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#566]
```[tasklist]
### Tasks
- [ ] [PY] Add Signing Step To Pipeline
- [ ] [PY] Create Official Microsoft Package in PYPI
- [ ] [PY] Publish Package
```

**Comment by blackchoey** [comment]
@aacebo move the task to public preview based on the discussion with you
