### ISSUE TITLE
[C#] Implement Activity handling fluent API, road to deprecating method override system.

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#569]
The fluent interface implementation in the JS SDK, is the direction that C# SDK should take. The general trend amongst .NET frameworks is to move towards fluent interface and using callbacks. Example:  [Minimal APIS](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/overview?view=aspnetcore-7.0). This interface relies heavily on method chaining to skip traditional scaffolding, and improve code legibility. 

Traditionally activity handlers are implemented by overriding specific methods. This can be confusing for multiple reasons. First, the routing process is convoluted and not apparent. Users will have to look into the codebase to understand how the incoming activity is routed. Plus, certain activity handler methods have routing logic, which the user can unintentionally override and cause issues. Secondly, registering multiple handlers for one activity is impossible.  
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/600
- [ ] https://github.com/microsoft/teams-ai/issues/611
- [ ] https://github.com/microsoft/teams-ai/issues/601
- [ ] https://github.com/microsoft/teams-ai/issues/602
- [ ] https://github.com/microsoft/teams-ai/issues/603
- [ ] https://github.com/microsoft/teams-ai/issues/604
- [ ] https://github.com/microsoft/teams-ai/issues/712
- [ ] https://github.com/microsoft/teams-ai/issues/713
- [ ] https://github.com/microsoft/teams-ai/issues/609
- [ ] https://github.com/microsoft/teams-ai/issues/607
- [ ] https://github.com/microsoft/teams-ai/issues/608
- [ ] https://github.com/microsoft/teams-ai/issues/710
- [ ] https://github.com/microsoft/teams-ai/issues/761
- [ ] https://github.com/microsoft/teams-ai/issues/696
- [ ] https://github.com/microsoft/teams-ai/issues/605
- [ ] https://github.com/microsoft/teams-ai/issues/697
- [ ] https://github.com/microsoft/teams-ai/issues/606
- [ ] https://github.com/microsoft/teams-ai/issues/610
- [ ] https://github.com/microsoft/teams-ai/issues/698
- [ ] https://github.com/microsoft/teams-ai/issues/744
- [ ] [C#] Performance, Thread-Safe, and Singleton
- [ ] https://github.com/microsoft/teams-ai/issues/800
```

**Comment by corinagum** [comment]
API should match JS for
- adaptive cards
- task modules
methods

**Comment by swatDong** [comment]
## Proposal

Start from how the user code will be like.

```csharp
// Initialize
{
    // create a new Application
    const app = new Application(...);
    
    // use fluent API to register activity handler
    app.Message("hello", (context, state, _) => {...});
    app.AdaptiveCards.ActionExecute("ok", (context, state, data, _) => {...});
    
    // import AI actions
    app.AI.ImportActions(...);
}

// In Controller
public async Task PostAsync()
{
    // call app for bot
    await adapter.ProcessAsync(Request, Response, app);
}
```

### Questions

Based on the above user code, may consider these questions which impact the final API design.

1. Add `ApplicationBuilder` or direct use `Application`? `Builder` is also a pattern to create immutable instance by calling `new XxxBuilder()` => `builder.AddXxx()/UseXxx()` => `builder.Build()` (e.g., ASP.NET Core's `WebApplicationBuilder`, Semantic Kernal's `KernalBuilder`). Do we expect `Application`'s handlers are mutable after app is running?

1. Method naming. For example, just "Message", or more clear such as "AddMessageRoute", or "MapMessage", or any else?

1. Should AI action import be fluent as well? The JS one is fluent, but in .NET we followed SK to use attribute for action import.

### Non-API work

Besides fluent API itself, these work items are required as well.

1. Ensure `Application` can work as singleton.

   1. Ensure `AI` (and its properties, sub-properties), `TurnStateManager`, `TypingTimer` are thread-safe

   1. Make `TypingTimer` work per turn (not globally start/stop)

1. Release plan. Since fluent API will be a breaking change. Do we need a separate branch? What's the package version number?

### API Design

A rough design and maybe tweak during implementation. For creating work items.

**Router**

```csharp
// The RouteSelector delegate
delegate Task<bool> RouteSelector(ITurnContext turnContext, CancellationToken cancellationToken);

// The RouteHandler delegate
delegate Task RouteHandler<TState>(ITurnContext turnContext, TState turnState, CancellationToken cancellationToken);

// Equivalent to `(string | RegExp | RouteSelector)[]` in JS
class MultipleRouteSelector
{
    string[]? Strings;
    Regex[]? Regexes;
    RouteSelector[]? Selectors;
}
```

**Application**

```csharp
// Application still need to be an `IBot` to be connected to Adapter
class Application<TState, TTurnStateManager> : IBot
    where TState : ITurnState<StateBase, StateBase, TempState>
    where TTurnStateManager : ITurnStateManager<TState>, new()
{
    // Equivalent to `app.adaptiveCards`, `app.messageExtensions`, `app.taskModules` in JS
    AdaptiveCards { get; }
    MessageExtensions { get; }
    TaskModules { get; }

    AddRoute(RouteSelector selector, RouteHandler<TState> handler, bool isInvokeRoute = false)

    // Different overloads for different selector types
    Activity(string type, RouteHandler<TState> handler)
    Activity(Regex regex, RouteHandler<TState> handler)
    Activity(RouteSelector selector, RouteHandler<TState> handler)
    Activity(MultipleRouteSelector selectors, RouteHandler<TState> handler)

    // More Methods ... should have overloads as well
    ConversationUpdate(...)
    Message(...)
    MessageReactions(...)
    Turn(...)
}
```

**AdaptiveCards**

```csharp
// Create delegate to represent handler if needed
delegate Task<ActionExecuteResult> ActionExecuteHandler<TState>(ITurnContext turnContext, TState turnState, object data, CancellationToken cancellationToken)

// Methods ... should have overloads for different selector types
ActionExecute(...)
ActionSubmit(...)
Search(...)
```

**MessageExtensions**

```csharp
// Create delegate to represent handler if needed
delegate...

// Methods ... should have overloads for different selector types
AnonymousQueryLink(...)
BotMessagePreviewEdit(...)
BotMessagePreviewSend(...)
FetchTask(...)
Query(...)
QueryLink(...)
SelectItem(...)
SubmitAction(...)
```

**TaskModules**

```csharp
// Create delegate to represent handler if needed
delegate...

// Methods ... should have overloads for different selector types
Fetch(...)
Submit(...)
```

**Comment by singhk97** [comment]
Reach out to John Taylor on making the Application class a singleton.
