### ISSUE TITLE
[JS] Implement the ApplicationBuilder class

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#639]
```[tasklist]
### Tasks
- [x] Confirm understanding of scenarios and desired functionalities
- [x] Review JS codebase and understand components
- [x] Devise and execute implementation for ApplicationBuilder class
- [x] Write unit tests for ApplicationBuilder class
```
