### ISSUE TITLE
[JS] Implement Auth

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#669]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/738
- [ ] https://github.com/microsoft/teams-ai/issues/739
- [x] https://github.com/microsoft/teams-ai/issues/783
- [ ] https://github.com/microsoft/teams-ai/issues/781
- [ ] https://github.com/microsoft/teams-ai/issues/782
- [ ] https://github.com/microsoft/teams-ai/issues/817
- [ ] https://github.com/microsoft/teams-ai/issues/890
- [ ] https://github.com/microsoft/teams-ai/issues/895
```
