### ISSUE TITLE
[C#] Refactor per ApplicationBuilder

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#710]
```[tasklist]
### Tasks
- [x] Add ApplicationBuilder class and associated tests
- [x] Modify instantiation of Application in 2 samples - 04.ai.b.messageExtensions.AI-ME and 04.e.twentyQuestions
- [x] Update corresponding READMEs and getting started docs
```
