### ISSUE TITLE
[C#] AI breaking changes

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#714]
This issue tracks all the AI system related breaking changes that will have to be ported over from JS.

Higher work items should be picked up before the lower ones.

Note: We will NOT be using `Semantic Kernel` as an implementation detail.

Planned flow for completing these tasks:
1. Teams functionality = `dotnetfluent` branch.
2. MVP breaking changes = `breaking-changes-1` branch.
3. Other breaking changes  =`breaking-changes-2` branch.

- The dependency tree looks like `dotnetfluent` -> `breaking-changes-1` -> `breaking-changes-2`.
- Once `dotnetfluent` is implemented it should be merged into main, and `breaking-changes-1` should sync with main.
- Once `breaking-changes-1` is implemented it should be merged into main and `breaking-changes-2` should sync with main.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/716
- [ ] https://github.com/microsoft/teams-ai/issues/715
- [ ] https://github.com/microsoft/teams-ai/issues/717
- [ ] https://github.com/microsoft/teams-ai/issues/794
- [ ] https://github.com/microsoft/teams-ai/issues/718
- [ ] https://github.com/microsoft/teams-ai/issues/719
- [ ] https://github.com/microsoft/teams-ai/issues/721
- [ ] https://github.com/microsoft/teams-ai/issues/720
- [ ] https://github.com/microsoft/teams-ai/issues/728
- [ ] https://github.com/microsoft/teams-ai/issues/722
- [ ] https://github.com/microsoft/teams-ai/issues/723
- [ ] https://github.com/microsoft/teams-ai/issues/724
- [ ] https://github.com/microsoft/teams-ai/issues/725
- [ ] https://github.com/microsoft/teams-ai/issues/726
- [ ] https://github.com/microsoft/teams-ai/issues/727
- [ ] https://github.com/microsoft/teams-ai/issues/798
- [ ] https://github.com/microsoft/teams-ai/issues/729
- [ ] https://github.com/microsoft/teams-ai/issues/848
- [ ] https://github.com/microsoft/teams-ai/issues/869
- [ ] https://github.com/microsoft/teams-ai/issues/873
- [ ] https://github.com/microsoft/teams-ai/issues/874
```
