### ISSUE TITLE
[C#] [JS Breaking changes] Models

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#723]
Entire `models`/ folder. Please add a task list of the .ts files tracking the porting process.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/pull/828
- [ ] Colorize the output
- [ ] Add unit test
```

**Comment by aacebo** [comment]
callout: I have been adding these models one by one with my other PRs so many of them exist in the `breaking-changes-2` branch

**Comment by kuojianlu** [comment]
> callout: I have been adding these models one by one with my other PRs so many of them exist in the `breaking-changes-2` branch

@aacebo Ooops, just saw your comments. I've just created a PR for `OpenAIModel`: https://github.com/microsoft/teams-ai/pull/828. Based on the latest `breaking-changes-2`, my PR does not do any duplicating works. Not sure if you've done any parts of `OpenAIModel` on your local changes. Hope we do not do duplicating works.
