### ISSUE TITLE
[C#] [JS Breaking changes] Update samples

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#729]
Update all the samples to use the `ActionPlanner` and deprecate the `OpenAIPlanner` and `AzureOpenAIPlanner`.

_NOTE:_ All the auth samples will be in a separate PR.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/857
- [ ] https://github.com/microsoft/teams-ai/issues/875
- [ ] https://github.com/microsoft/teams-ai/issues/876
- [ ] https://github.com/microsoft/teams-ai/issues/879
- [ ] https://github.com/microsoft/teams-ai/issues/881
- [ ] https://github.com/microsoft/teams-ai/issues/882
- [ ] https://github.com/microsoft/teams-ai/issues/884
- [ ] https://github.com/microsoft/teams-ai/issues/898
- [ ] https://github.com/microsoft/teams-ai/issues/923
- [ ] https://github.com/microsoft/teams-ai/issues/938
- [ ] https://github.com/microsoft/teams-ai/issues/940
- [ ] https://github.com/microsoft/teams-ai/issues/941
```
