### ISSUE TITLE
[C# Port] Main Task List

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#82]
- [X] Activity Handler System

- [X] Typing Timer

- [X] AI Module - (Planner, PromptManager, ResponseParser, Moderator, HTTPClients, Action System)
  - [x] Response Parser
  - [X] OpenAIPlanner 
  - [X] AzureOpenAIPlanner
  - [X] Prompt Manager
  - [X] OpenAIModerator
  - [x] AzureOpenAIModerator (currently not needed for parity)
  - [x] Main AI Class Tests
  - [x] OpenAIModerator Tests
  - [X] All other AI tests
- [x] Turn State Infrastructure

C#/JS SDK Discrepancy list:
* SK azure client doesn't support configuring the api version in C#.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/207
- [ ] https://github.com/microsoft/teams-ai/issues/208
- [ ] https://github.com/microsoft/teams-ai/issues/117
- [ ] https://github.com/microsoft/teams-ai/issues/209
- [ ] https://github.com/microsoft/teams-ai/issues/210
- [ ] https://github.com/microsoft/teams-ai/issues/212
- [ ] https://github.com/microsoft/teams-ai/issues/213
- [ ] https://github.com/microsoft/teams-ai/issues/219
- [ ] https://github.com/microsoft/teams-ai/issues/264
```

**Comment by singhk97** [comment]
Resuming C# Port efforts. Will have separate work item for each PR instead of tracking all of it in one work item.

**Comment by singhk97** [comment]
Moving separate work items back into this issue to keep things compact
