### ISSUE TITLE
Post GA - User Authentication

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#893]
```[tasklist]
### Tasks
- [ ] Fix bot authentication bug with multiple connections - ambiguous routing of `signin/verifyState` and `signin/tokenExchange`
- [ ] Fix race condition authentication bug when user tries to sign in. If a second incoming request is sent before the state is changed to "in auth flow".
- [ ] https://github.com/microsoft/teams-ai/issues/964
- [ ] https://github.com/microsoft/teams-ai/issues/1121
```

**Comment by aacebo** [comment]
@singhk97 is this up to date and still relevant?

**Comment by singhk97** [comment]
Moved task list to Authentication epic [#1102](https://github.com/microsoft/teams-ai/issues/1102). Closing this ticket.
