### ISSUE TITLE
[JS] Bug Bash Revisions

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#916]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/922
- [ ] https://github.com/microsoft/teams-ai/issues/931
- [ ] https://github.com/microsoft/teams-ai/issues/966
- [ ] https://github.com/microsoft/teams-ai/issues/930
- [ ] https://github.com/microsoft/teams-ai/issues/934
- [ ] https://github.com/microsoft/teams-ai/issues/919
```

**Comment by lilyydu** [comment]
Updating docs and bug bashing required for most/all of these tickets as well.
