### ISSUE TITLE
[JS] Update setup for samples

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#922]
1. Add sample.env 
2. Remove the AI-related vars from the local YMLs.
3. Remove yarn install and build in YMLs
4. Remove duplicate key names in logic 
5. Fix references for MicrosoftAppId, MicrosoftAppPassword. Replace with BOT_ID, and BOT_PASSWORD in logic and YML - respectively. _NOTE:_ might need to update how the adapter is created.
6. Update docs for set up instructions - just like how it's done in Math Bot & Chat Moderation.

No. 6 examples:
- Incorrect descriptions
- Missing table of contents
- Typos

No. 6 example bot PR: https://github.com/microsoft/teams-ai/pull/969/files#diff-155c7061e7d0a0889267fc8c01cc0dc96ccb57b99ebdf5e651b69f345134a12f 

Idea: match WhoBot flow with population of variables.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/967
- [ ] https://github.com/microsoft/teams-ai/issues/968
- [ ] https://github.com/microsoft/teams-ai/issues/970
- [ ] https://github.com/microsoft/teams-ai/issues/971
- [ ] https://github.com/microsoft/teams-ai/issues/972
- [ ] https://github.com/microsoft/teams-ai/issues/974
- [ ] https://github.com/microsoft/teams-ai/issues/985
- [ ] https://github.com/microsoft/teams-ai/issues/977
- [ ] https://github.com/microsoft/teams-ai/issues/976
- [ ] https://github.com/microsoft/teams-ai/issues/978
- [ ] https://github.com/microsoft/teams-ai/issues/979
- [ ] https://github.com/microsoft/teams-ai/issues/980
- [ ] https://github.com/microsoft/teams-ai/issues/981
- [ ] https://github.com/microsoft/teams-ai/issues/982
- [ ] https://github.com/microsoft/teams-ai/issues/983
- [ ] https://github.com/microsoft/teams-ai/issues/984
- [ ] https://github.com/microsoft/teams-ai/issues/1015
```
