### ISSUE TITLE
JS SDK Post GA Epic

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#953]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/954
- [ ] https://github.com/microsoft/teams-ai/issues/958
- [ ] https://github.com/microsoft/teams-ai/issues/1017
- [ ] https://github.com/microsoft/teams-ai/issues/829
- [ ] https://github.com/microsoft/teams-ai/issues/914
- [ ] https://github.com/microsoft/teams-ai/issues/1137
- [ ] https://github.com/microsoft/teams-ai/issues/1085
- [ ] https://github.com/microsoft/teams-ai/issues/1086
- [ ] https://github.com/microsoft/teams-ai/issues/54
- [ ] https://github.com/microsoft/teams-ai/issues/1009
- [ ] https://github.com/microsoft/teams-ai/issues/454
- [ ] https://github.com/microsoft/teams-ai/issues/801
- [ ] https://github.com/microsoft/teams-ai/issues/1087
- [ ] https://github.com/microsoft/teams-ai/issues/1136
```

**Comment by corinagum** [comment]
Closing as Build is complete
